# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/android
pool:
  vmImage: 'macOS-10.14'
variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'
  system.debug: true

steps:
- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'app.mobileprovision'
    removeProfile: true

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default'
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    packageApp: true
    

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    # gradleOptions: '-Xmx3072m'
    gradleOpts: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
  displayName: Copy .apk files to artifact staging directory

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github'
    repositoryName: 'agrim4s/pipelines-android'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: userSpecifiedTag  
    tag: '$(Build.BuildNumber)'  
    title: '$(Build.BuildNumber)'  
    assets: '**/*.*p*'  
    changeLogCompareToRelease: lastNonDraftRelease  
    changeLogType: 'commitBased'



- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'app-mock'
    artifactType: 'container'
  displayName: Publish artifacts
